### ISSUE TITLE
Django >= 1.9 compatibility

### ISSUE THREAD

**Issue by paravoid** [peeringdb/django-peeringdb#16]
Django 1.7 deprecated `./manage.py syncdb`, in favor of `./manage.py migrate` and Django 1.9 onwards just dropped syncdb entirely. django-peeringdb doesn't ship any migrations, though, which has the effect of a plain `./manage.py migrate` not creating any tables and thus pdb_sync etc. failing. If one runs `./manage.py makemigrations` and then migrate it works, but of course this creates a migration in one's environment (virtual or not) and relies on permissions.

I found out that there is a `./manage.py migrate --run-syncdb` too, which actually does the trick:
```
Operations to perform:
  Synchronize unmigrated apps: django_peeringdb, messages, staticfiles
  Apply all migrations: admin, auth, contenttypes, peercollect, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table peeringdb_organization
    Creating table peeringdb_facility
    Creating table peeringdb_network
    Creating table peeringdb_ix
    Creating table peeringdb_ix_facility
    Creating table peeringdb_ixlan
    Creating table peeringdb_ixlan_prefix
    Creating table peeringdb_network_contact
    Creating table peeringdb_network_facility
    Creating table peeringdb_network_ixlan
    Running deferred SQL...
Running migrations:
  No migrations to apply.
```
I'm not sure if it's the kosher way to do things in Django, though. If it is, it should probably be documented for others to not scratch their heads as I did :)

**Comment by vegu** [comment]
Thanks for the feedback, i think we will definitely want to add migration files to the repo at this point. It was brought up when we upgraded the peeringdb server to django 1.11 - which uses this module for it's abstract models, and handles it's own migrations. It'd make sense to maintain migrations for the concrete models in this repo.

**Comment by paravoid** [comment]
I think I know what's up with that: the migrations in the tree were created with Python 2, and Django automatically adds `from __future__ import unicode_literals` to the migration, even if the models didn't. This resulted into stuff like `help_text=b'Latitude'` (note the `b''`). When I run `makemigrations` on Python3 system, Python interprets that as a change, and wants to convert these to (what are now) strings.
