### ISSUE TITLE
Problem after upgrading package from 0.4 to 0.7

### ISSUE THREAD

**Issue by eloos** [peeringdb/django-peeringdb#19]
I installed the new version (0.4.0.1->0.7.0.1) of django-peeringdb. Afterwards I ran in the directory of my app where I also integrate PDB python manage.py makemigrations and I get the following error
OSError: [Errno 20] Not a directory: '/Users/eric/projects/starling-dev/lib/python2.7/site-packages/django_peeringdb-0.7.0.1-py2.7.egg/django_peeringdb/migrations'

Obviously the egg file does not have a directory, if I unzip the egg, I run into a next issue:
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration app.0001_initial is applied before its dependency django_peeringdb.0001_initial on database 'default'.

**Comment by vegu** [comment]
Sounds to be same/similar issue as https://github.com/peeringdb/django-peeringdb/issues/16 - Can you check the workaround posted there and report back. Thanks

**Comment by grizz** [comment]
Released 0.8.0 which should fix it.
