### ISSUE TITLE
TIME_ZONE = 'America/Chicago'

### ISSUE THREAD

**Issue by steffann** [peeringdb/django-peeringdb#38]
The default TIME_ZONE of Django is `America/Chicago`. Combined with stripping the timezone data from the API this causes all timestamps to be saved in the database with a weird offset. At least in PostgreSQL where Django always stores timestamps in UTC.

Adding `TIME_ZONE='UTC'` to `default_settings.py` solves this.

**Comment by job** [comment]
It makes sense to me to run all the things in UTC
