### ISSUE TITLE
Add a Django admin interface view

### ISSUE THREAD

**Issue by grizz** [peeringdb/django-peeringdb#63]
From PR #54 

This is helpful for people using this to manage their own local copy.

We will have to verify how it interacts with the production server code, but looks great other wise.

+1 from me -- @peeringdb/pc please vote

**Comment by ynbrthr** [comment]
+1

**Comment by mcmanuss8** [comment]
+1

**Comment by egfrank** [comment]
Moving to 4: Ready for Implementation so 20c can codereview and test
