### ISSUE TITLE
Add __str__ methods to more models

### ISSUE THREAD

**Issue by grizz** [peeringdb/django-peeringdb#65]
PR #52 

We'll need to verify how this works with the production server, but looks good to me.

+1

@peeringdb/pc please vote.

**Comment by arnoldnipper** [comment]
What do the __str__ methods do?

**Comment by shane-kerr** [comment]
> What do the **str** methods do?

The `__str__` methods in Python are what get called whenever you try to convert something to a string, either explicitly by using `str()` or implicitly like when you use `print()`.

The default conversion is pretty ugly:
```
>>> class x: pass
... 
>>> y = x()
>>> str(y)
'<__main__.x object at 0x7fe05b322f70>'
```
So it's usually a nice idea to define these and convert to something a human can use.

**Comment by shane-kerr** [comment]
+1

**Comment by ynbrthr** [comment]
+1

**Comment by egfrank** [comment]
Moving to 4: Ready for implementation so 20c can code review and test

**Comment by egfrank** [comment]
Placing in 3a while we wait for changes in response to code review
