### ISSUE TITLE
ORM configuration Options is missing (postgreSQL)

### ISSUE THREAD

**Issue by ObservabilityTeam** [peeringdb/django-peeringdb#98]
Hi,

We are integrating peeringdb to our internal tool-set. We are using a postgresql database with multiple schema to organize multiple sources included peeringdb.

We manage to sync without any problems to the public schema, but we would like to create a specific schema peeringdb.

In order to sync Peeringdb data in a schema other than 'public', we had to add the OPTIONS argument to the config.yaml (as in code below). The current version only allows the parameters below (new field with ->).

```python
DJANGO_DB_FIELDS = (
    "ENGINE",
    "NAME",
    "HOST",
    "PORT",
    "USER",
    "PASSWORD",
->  "OPTIONS")
```

from the following file: https://github.com/peeringdb/django-peeringdb/blob/main/src/django_peeringdb/client_adaptor/load.py

For the case we want to implement, the final configuration after adding the OPTIONS will look something as follows, meaning  sync in a specific schema:

```yaml
orm:
  backend: django_peeringdb
  database:
      engine: postgresql
      host: localhost
      name: peeringdb
      user: peeringdb
      password: supers3cr3t
->    options:
->         options: '-c search_path=peeringdb_schema'  
```
Please check the following list of possible options: https://docs.djangoproject.com/en/5.0/ref/databases/#postgresql-connection-settings

The change described before will allow to more granular configurations not just for PostgreSQL but also for other databases and therefore more flexibility for the final users.

Thank you!

**Comment by floatingstatic** [comment]
+1
I would like to be able to set `'OPTIONS': {'sslmode': 'require'}` for postgres and this does not appear to be possible at the moment without a code change.

**Comment by grizz** [comment]
Good call -- +1

**Comment by jackcarrozzo** [comment]
+1

**Comment by arnoldnipper** [comment]
+1
